apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20231022021145.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20231022021145.0.0+build.02e9424
  releaseNotes: |
    Release v20231022021145.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-21-10-2023-22-51-00-455092395/where-for-dinner-search-my-apps-bundle@sha256:01c24b206e1e02b66e60f8535fe90e3c9a76c688871bf3165d824e7d053aca8d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

