apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231022021126.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231022021126.0.0+build.02e9424
  releaseNotes: |
    Release v20231022021126.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-21-10-2023-22-51-00-455092395/where-for-dinner-my-apps-bundle@sha256:df2828672232cb098aaf4a7efd685625ceda574c2e34de9c3a9036a409dbee9b
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

