apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20231022021112.0.0+build.02e9424
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20231022021112.0.0+build.02e9424
  releaseNotes: |
    Release v20231022021112.0.0+build.02e9424 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-21-10-2023-22-51-00-455092395/where-for-dinner-availability-my-apps-bundle@sha256:f3dafc19561d4432031ff3886cc18f2041b4e693371134a5677aac5a8cb78d9b
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

